spring.application.name=noreco1-firefly-v2
spring.main.allow-bean-definition-overriding=true

app.mysql.driver=com.mysql.cj.jdbc.Driver
app.mysql.url=jdbc:mysql://localhost:3306/noreco1_firefly?serverTimezone=UTC
app.mysql.username=root
app.mysql.password=tsi-KEN04@2009
app.mysql.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#app.mysql2.driver=com.mysql.cj.jdbc.Driver
#app.mysql2.url=jdbc:mysql://127.0.0.1:3306/firefly_noreco1?useSSL=false&allowPublicKeyRetrieval=true
#app.mysql2.username=root
#app.mysql2.password=
#app.mysql2.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

path.attachments=C:\\Users\\TSI-KEN04\\Downloads\\firefly-dir\\
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=512MB
spring.servlet.multipart.max-request-size=512MB
spring.jackson.serialization.fail-on-empty-beans=false

server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,application/pdf
url.base=http://firefly-no1.test:8081

app.jwtSecret=Pe+ioqVR7mA9uBvxT2XO9vDNed1PekBgt0Kpc8wm+j3DsWDyvjpO94TpTnVoZucs5BqnZfnF8nQwHCicfcVjhg==
app.jwtExpirationMs=86400000

iso.certification=ISO9001-2015

spring.thymeleaf.check-template-location=false
spring.messages.basename=messages

logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=DEBUG

server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-exception=true

# See the actual values being bound (column values per row)
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# See transaction begin/commit/rollback events
logging.level.org.springframework.transaction=DEBUG
